"""initial schema

Revision ID: 8924286b406b
Revises: 
Create Date: 2026-08-16 11:10:15.620916

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8924286b406b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('RENEWABLE_ENERGY_PLANNER', 'GIS_ANALYST', 'PROJECT_MANAGER', 'ADMINISTRATOR', name='userrole'), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('land_area_hectares', sa.Float(), nullable=True),
    sa.Column('elevation_meters', sa.Float(), nullable=True),
    sa.Column('existing_infrastructure', sa.String(length=500), nullable=True),
    sa.Column('land_ownership', sa.String(length=255), nullable=True),
    sa.Column('solar_suitability_score', sa.Float(), nullable=True),
    sa.Column('wind_suitability_score', sa.Float(), nullable=True),
    sa.Column('infrastructure_score', sa.Float(), nullable=True),
    sa.Column('investment_score', sa.Float(), nullable=True),
    sa.Column('overall_deployment_score', sa.Float(), nullable=True),
    sa.Column('suitability_category', sa.Enum('EXCELLENT', 'HIGHLY_SUITABLE', 'MODERATELY_SUITABLE', 'LOW_SUITABILITY', 'UNSUITABLE', name='suitabilitycategory'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
